@startuml View messages
title View all messages
skinparam Style strictuml
collections Client
collections Controller as app.rb
collections Model as MessageBoard
collections View as erb

Client -> app.rb : POST request
app.rb -> MessageBoard : .create
MessageBoard --> app.rb : (new message)
app.rb -> erb : (new message)
erb --> app.rb : html
app.rb --> Client : response

@enduml